name: first_workflow
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
    
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm run test
      - name: Run message
        run: echo "Testing..."
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Build Projecy
        run: npm run build
      - name: Run message
        run: echo "Building Projecto..."
